//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base2.Mantis.SeleniumWebdriverTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base2.Mantis.SeleniumWebdriverTest.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A necessary field &quot;Description&quot; was empty. Please recheck your inputs..
        /// </summary>
        internal static string msgBugCampoDescricaoObrig {
            get {
                return ResourceManager.GetString("msgBugCampoDescricaoObrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A necessary field &quot;Summary&quot; was empty. Please recheck your inputs..
        /// </summary>
        internal static string msgBugCampoSumarioObrig {
            get {
                return ResourceManager.GetString("msgBugCampoSumarioObrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful..
        /// </summary>
        internal static string msgBugSucesso {
            get {
                return ResourceManager.GetString("msgBugSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete these issues?.
        /// </summary>
        internal static string msgExcluirBug {
            get {
                return ResourceManager.GetString("msgExcluirBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account may be disabled or blocked or the username/password you entered is incorrect..
        /// </summary>
        internal static string msgLoginInvalido {
            get {
                return ResourceManager.GetString("msgLoginInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as: ramon.souza (Ramon Souza - manager).
        /// </summary>
        internal static string msgLoginSucesso {
            get {
                return ResourceManager.GetString("msgLoginSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number was expected for bug_id..
        /// </summary>
        internal static string msgNumeroBugNaoExiste {
            get {
                return ResourceManager.GetString("msgNumeroBugNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Issue Details [ Jump to Notes ] [ Send a reminder ].
        /// </summary>
        internal static string msgVerBug {
            get {
                return ResourceManager.GetString("msgVerBug", resourceCulture);
            }
        }
    }
}
